{"uuid": "137bb44b-e4df-496c-be60-d83799aa850f", "children": ["317b61a7-8a54-46e8-a59e-9324eac3c950"], "befores": [{"name": "admin_driver", "status": "passed", "start": 1688358618398, "stop": 1688358621445}], "afters": [{"name": "admin_driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 请填写年利率\nMessage: unexpected alert open: {Alert text : 请填写年利率}\n  (Session info: chrome=114.0.5735.199)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0049A813+48355]\n\t(No symbol) [0x0042C4B1]\n\t(No symbol) [0x00335358]\n\t(No symbol) [0x0038CDAD]\n\t(No symbol) [0x0037A536]\n\t(No symbol) [0x003582DC]\n\t(No symbol) [0x003593DD]\n\tGetHandleVerifier [0x006FAABD+2539405]\n\tGetHandleVerifier [0x0073A78F+2800735]\n\tGetHandleVerifier [0x0073456C+2775612]\n\tGetHandleVerifier [0x005251E0+616112]\n\t(No symbol) [0x00435F8C]\n\t(No symbol) [0x00432328]\n\t(No symbol) [0x0043240B]\n\t(No symbol) [0x00424FF7]\n\tBaseThreadInitThunk [0x76927D59+25]\n\tRtlInitializeExceptionChain [0x77AEB74B+107]\n\tRtlClearBits [0x77AEB6CF+191]\n\n", "trace": "  File \"D:\\pythonProjectweb_232\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\pythonProjectweb_232\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\pythonProjectweb_232\\conftest.py\", line 52, in admin_driver\n    save_cookies(driver)\n  File \"D:\\pythonProjectweb_232\\commons\\utils.py\", line 37, in save_cookies\n    cookies = driver.get_cookies()\n  File \"D:\\pythonProjectweb_232\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 675, in get_cookies\n    return self.execute(Command.GET_ALL_COOKIES)[\"value\"]\n  File \"D:\\pythonProjectweb_232\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\pythonProjectweb_232\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 244, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1688358643409, "stop": 1688358643413}], "start": 1688358618398, "stop": 1688358643413}